# Test Client Configuration
# Development URL
BASE_URL=http://localhost:8081/portakalapi

# Your API key (get from web dashboard after registering)
API_KEY= NI-4NIzXwbk4XxHd2ZLXVagyU_dGdUYGxpZcl0-_ecA

# Test data
REACTOR_NAME=Test Reactor 1
REACTOR_ADDRESS=test-reactor-001
BATTERY_NAME=Test Battery 1
BATTERY_ADDRESS=test-battery-0011